<?php
/* Don't edit manually. This is generated by "prepare-php.js". */
$lang = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);

$basePath = "/projects/static-next-app/out";
$path = $_SERVER['REQUEST_URI'];
$path = str_replace($basePath, '', $path);

switch ($lang){
    case "en": 
        header("Location: ". $basePath . "/en" . $path);
        break;
    case "de": 
        header("Location: ". $basePath . "/de" . $path);
        break;
    case "fr": 
        header("Location: ". $basePath . "/fr" . $path);
        break;
    default:
        header("Location: ". $basePath . "/en" . $path);
        break;
}