import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Language, languages } from "@/lib/translations"
import nextConfig from "@/next.config.mjs"
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] })

export function generateStaticParams() {
    return languages.map((lang) => ({ lang }))
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({
    children,
    params
}: Readonly<{
    children: React.ReactNode
    params: { lang: Language }
}>) {
    return (
        <html lang={params.lang}>
            <head>
                <base href={`${nextConfig.basePath}/`} />
            </head>
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}
