import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Language, languages } from "@/lib/translations"
import nextConfig from "@/next.config.mjs"

const inter = Inter({ subsets: ["latin"] })

export function generateStaticParams() {
    return languages.map((lang) => ({ lang }))
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({
    children,
    params
}: Readonly<{
    children: React.ReactNode
    params: { lang: Language }
}>) {
    return (
        <html lang={params.lang}>
            <head>
                <base href={`${nextConfig.basePath}/`} />
            </head>
            <body className={inter.className}>
                <header>
                    <nav>
                        <ul>
                            <li>
                                <a href=".">Home</a>
                            </li>
                            <li>
                                <a href="about">About</a>
                            </li>
                        </ul>
                    </nav>
                </header>
                {children}
            </body>
        </html>
    )
}
